### ISSUE TITLE
Contact Page

### ISSUE THREAD

**Issue by nniiicc** [OpenDataLiteracy/site#15]
- Remove the submission form (we don't have it connected
- Add contact info for our project
- Add relevant photo (no idea - something of UW -> http://staff.washington.edu/paymana/images/photos/uw/mountain4.gif)

**Comment by norlab** [comment]
@nniiicc 
I can either change the "Contact" link to a an email link or add contact info to the existing "Contact" page. What email address should we use?

**Comment by norlab** [comment]
Removed contact page
