### ISSUE TITLE
Date for Internship Event

### ISSUE THREAD

**Issue by nniiicc** [OpenDataLiteracy/site#2]
Send doodle poll to sponsors and students

**Comment by nniiicc** [comment]
Shoot for Aug 14-18th

**Comment by norlab** [comment]
Email sent 6/21:

Hello ODL Interns and Sponsors!

My name is Bree and I am excited to be assisting with the Open Data Literacy program this summer. While I know that you have just begun your projects this summer, we are already planning the showcase for the completion of the projects. The showcase will be an opportunity to present your work to fellow interns, sponsors, and other stakeholders in the program. After reviewing the dates of availability for each of the interns, we have come up with two possibilities for the showcase date and time:

August 14, 1:00-4:00
August 15, 1:00-4:00

The event will be held on the University of Washington campus (specific location TBD). Please let me know if you are available for either or both of those times and we will solidify the plans.

I'm looking forward to working with all of you!

**Comment by norlab** [comment]
David Doyle: Either 
Gordon Kennedy: Either
Will Saunders: Either + Guests
Nina Showell: Either
Tim Blankemeyer: Either
Wynnie Tran: Prefers Aug 15th

**Comment by nniiicc** [comment]
Great - thanks for getting this out Bree - We can follow up with another email once we've got the date down and let people know details (and that of course they can bring guests!)

**Comment by nniiicc** [comment]
Looks like Aug 15 it is... Closing now.
