### ISSUE TITLE
Venue for Internship Event 

### ISSUE THREAD

**Issue by nniiicc** [OpenDataLiteracy/site#3]

**Comment by norlab** [comment]
Suzzallo Peterson Room - as of 6/23 available [Aug 15](https://outlook.office365.com/owa/calendar/70ef1140f7064f5aae4a6def702e3c56@uw.edu/9626c7038dd64ca8adb7a0c162aad7dc10690670122481866206/calendar.html)
[Details](http://www.lib.washington.edu/services/facilities/meetingrooms/petersen)
Suzzallo Smith Room - as of 6/23 available [Aug 14 AND 15](https://outlook.office365.com/owa/calendar/af2bf3b8ba0545a79fb4f71adaa9a606@uw.edu/a621a00e5fda4d2b9c6ebde294c383998480309392658605261/calendar.html)
[Details](http://www.lib.washington.edu/services/facilities/meetingrooms/smith)

Will scope out other room on Monday 6/26

**Comment by norlab** [comment]
I wandered the Architecture Building and Denny Hall but did not find a meeting space as nice as the Petersen or Smith Rooms in Suzzallo. The Smith Room is currently available on August 14 and 15 and Petersen is available on August 15. Both are $60/hour with additional fees if we need furniture set up.

I believe we were discussing a partner lunch prior to the showcase? We could reserve the room from 12:00 - 4:00 to include lunch, presentations, coffee/tea.

**Comment by norlab** [comment]
The following room rental request has been submitted:

--- Room Requested ---
Preferred Room
    Petersen Room
If other, which Suzzallo or Allen room/location
--- Event Information ---
Name of Event
    Open Data Literacy Showcase
Set-up Start Date/Time
    Aug 15, 2017 01:30 PM
Event Start Day/Time
    Aug 15, 2017 02:00 PM
Event End Date/Time
    Aug 15, 2017 04:30 PM
Set-up End Date/Time
--- Event Set-Up ---
Expected Number of Attendees
    40
Room Set-Up
    Reception Set-Up
Set-up Specifications
    We are not entirely sure of the number of seats needed. We envision a reception set up in which presentations can be given to the whole room.
If additional chairs or tables will be needed, how many?
Will a projection screen be needed?
    Yes
Do you need a podium?
    Yes
Additional set-up requests
--- Catering Information ---
Will catering be used?
    Yes
Caterer's Name
    unsure
Caterer's Phone Number
Delivery Time
Return Time for Pick-Up
Will alcohol be served?
    No
--- Reservation Contact ---
Your Name
    Bree Norlander
Title
    ODL Project Coordinator
Your E-Mail Address
    norlab@uw.edu
Phone Number
    425-698-7302
UW Department or UW Sponsor(s)
    iSchool
Address / UW Box Number
--- Budget / Authorization ---
UW Budget Number
    67-5285
UW Budget Name
    Open Data for Public Good (ODPG)
PCA Codes
Budget Contact Name
Budget Contact Email Address
Budget Contact Phone Number
Authorized Signature
    The above authorizes and approves charges to this budget

**Comment by norlab** [comment]
Hi Bree,

We have your 8/15 event confirmed on the Petersen Room calendar from 1:30 to 4:30. Let us know if you have any more info on your setup leading up to then.

Best,

Brad

 

Brad Van Horne, Facilities Program Coordinator,

Suzzallo & Allen Libraries

482 Allen Library|Box 352900 
Seattle, WA  98195-2900 | USA

Direct: 206-616-4126 | bvanhorn@uw.edu 
Department: 206-543-2009 | uwlib-facilities@uw.edu

**Comment by norlab** [comment]
MGH 224 reserved for business meeting 12:00-1:30
